---
title: "Hypothesis Testing"
author: "Easy Data Science"
date: "6/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(datasets)
library(tidyr)
library(ggthemes)
library(moments)
library(lubridate)
library(data.world)
```



## Hypothesis Testing



```{r}
x<-c(42,56,29,35,47,37,39,29,45,35,51,53)

# If population mean in 45
t.test(x = x,mu = 45,alternative = c("two.sided"),conf.level =0.95)
# If population mean < 45
t.test(x = x,mu = 45,alternative = c("less"),conf.level =0.95)
# If population mean > 45
t.test(x = x,mu = 45,alternative = c("greater"),conf.level =0.95)
```



```{r}
x =c(70,82,78,74,94,82)

y =c(64,72,60,76,72,80,84,68)

t.test(x, y,alternative =c("two.sided"),var.equal =TRUE)

?prop.test
```


```{r}
before <-rnorm(10,100,3)
after <-rnorm(10,110,3)

t.test(before, after, paired = TRUE, alternative = "two.sided")

```



```{r}

sat.custo<-c(100,120,125)
pro<-c("A","B","C")

chisq.test(sat.custo)

a<-rnorm(n=10,mean=7,sd=2)

b<-pnorm(seq(0.1,1,by=0.1), mean=3,sd=2)

chisq.test(x=a,p=b, rescale.p=T)

dt <- matrix(c(120, 90, 40, 110, 95, 45), ncol=3, byrow=TRUE)

rownames(dt)<-c("male","female")
colnames(dt)<-c("non_smoker","occ_smoker","chain_smoker")
dt<-as.table(dt)
chisq.test(dt)


```


