---
title: "Intro to Regression"
author: "Easy Data Science"
date: "6/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(datasets)
library(tidyr)
library(ggthemes)
library(moments)
library(lubridate)
library(data.world)
```





# Linear regression

```{r}
set.seed(123) 
x <- rnorm(50,mean=100,sd=20)
# y = 0.6 * x + noise
y <- 0.6 * x + rnorm(50,mean=0,sd=10)

data <- data.frame(x,y)

stde <- function(x){(x-mean(x))/sd(x)}

stdData <- 
  data%>% 
  mutate_all(funs(stde,mean,sd)) 

stdlm <- lm(y_stde ~ x_stde, data=stdData)

stdData$slope <- coef(stdlm)[2]
stdData$intercept <- coef(stdlm)[1]
stdData$y_hat <- (stdData$x_stde * stdData$slope) + stdData$intercept


stdData %>% 
  ggplot( aes(x=x_stde, y=y_stde)) +
  geom_point() +
  geom_abline(aes(slope=slope,intercept=intercept),show.legend=F) +
  geom_segment(aes(x=x_stde,y=y_stde,xend=x_stde,yend=y_hat),show.legend=F, linetype=2) +
  labs(
    title ="Linear Regression",
    y="",
    x=""
  ) +
  theme_clean()

dt<-mtcars
dt
plot(mpg~hp,dt)
fit1=lm(mpg~hp,data=dt)
fit1
summary(fit1)
plot(mpg~hp,dt)+
abline(fit1,col="red")

names(fit1)
confint(fit1)

predict(fit1,data.frame(hp=c(100,125,300)),interval="confidence")

fit2=lm(mpg~hp+wt,data=dt)
fit2
summary(fit2)
confint(fit2)
predict(fit2,data.frame(hp=c(100,125,300), wt=c(2,2.4,2.3)),interval="confidence")
plot(fit2)

fit3=lm(mpg~hp*wt,dt)
fit4=lm(mpg~hp+I(hp^2),dt)


summary(fit3)
summary(fit4)

plot(mpg~hp, data = dt)+
points(dt$hp,fitted(fit3),col="red",pch=20)+
points(dt$hp,fitted(fit4),col="blue",pch=20)
```

# Logistic Regresion

```{r}

glm.fit=glm(vs~hp+wt,
            data=mtcars,family=binomial)
summary(glm.fit)
glm.probs=predict(glm.fit,type="response") 
glm.probs[1:5]
glm.pred=ifelse(glm.probs>0.5,1,0)

table(glm.pred,mtcars$vs)
mean(glm.pred==mtcars$vs)



```


